### ISSUE TITLE
We need to organize the solutions

### ISSUE THREAD

**Issue by Oddjob922** [alfredmuffin/Beginner-Projects#12]
We should do it now so that later, so things can be more organized and appealing to others. I don't know how to do this without merge conflicts, as I am still a bit of a git noob. I'm thinking that we should have categories, and put each project into its category. For example we could have a numbers, games, and misc category.

**Comment by alfredmuffin** [comment]
We will do it today. We should also have one folder per project. We already have two solutions for a single project, and as we grow we will probably (and hopefully) have multiple solutions for each project in different languages.

So we should organize the project list in the README by categories, too, while also keeping them in order of increasing difficulty.

**Comment by Oddjob922** [comment]
Yeah I actually like that way better now that I think about it

**Comment by alfredmuffin** [comment]
I don't think we have enough projects yet to warrant organization by categories. I moved all the solutions to a corresponding project folder.
